repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.290
  hooks:
    - id: ruff
      stages: [commit,push]

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
    - id: black
      # It is recommended to specify the latest version of Python
      # supported by your project here, or alternatively use
      # pre-commit's default_language_version, see
      # https://pre-commit.com/#top_level-default_language_version
      language_version: python3.11
      stages: [push]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.981
  hooks:
    - id: mypy
      exclude: ^tests/
      args: [--strict]
      stages: [push]
