name: tts_framework
channels:
  - numba
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda-runtime=11.8.0
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkdocs-material=9.3.1
  - mkdocs-material-extensions=1.1.1
  - mypy=0.981
  - mypy_extensions=0.4.3
  - numba=0.58.0rc2
  - numpy=1.25.2
  - python=3.11.5
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - lightning=2.0.9
  - scikit-learn=1.2.2
  - scipy=1.11.1
  - torchaudio=2.0.2
  - torchmetrics=1.2.0
  - torchvision=0.15.2
  - tqdm=4.65.0
  - pip=23.2.1
  - pynini=2.1.5
  - pip:
      - datasets==2.14.5
      - deep-phonemizer==0.0.19
      - nemo-text-processing==0.2.0rc0
      - piq==0.8.0
      - soundfile==0.12.1
      - transformers==4.34.0
      - unidecode==1.3.7
