site_name: TTS-Framework
nav:
  - Home: index.md
  - Dev docs:
    - References: dev/readme.md
    - Change Log: dev/change_log.md
    - Problems and Fixes: dev/problems_and_fixes.md
    - Training: dev/training.md
    - Lightning docs:
      - References: dev/lightning/readme.md
      - Basic:
        - Argparse and Hyperparams: dev/lightning/basic/argparse_and_cli.md
        - Debug: dev/lightning/basic/debug.md
        - Early Stopping: dev/lightning/basic/early_stopping.md
        - Find Bottlenecks: dev/lightning/basic/find_bottlenecks.md
        - Saving Loading checkpoints: dev/lightning/basic/saving_loading_checkpoints.md
        - Visualize Experiments: dev/lightning/basic/visualize_experiments.md
      - Intermediate:
        - Hardware-Agnostic training: dev/lightning/intermediate/hardware_agnostic_training.md
        - GPU training: dev/lightning/intermediate/gpu_training.md
        - Lightning Data Module: dev/lightning/intermediate/lightning_data_module.md
        - Configure hyperparameters from the CLI: dev/lightning/intermediate/configure_hyperparameters_from_the_cli.md
        - Customize checkpointing behavior: dev/lightning/intermediate/customize_checkpointing_behavior.md
        - Track and Visualize Experiments: dev/lightning/intermediate/track_and_visualize_experiments.md
        - SOTA scaling techniques (N-Bit Precision): dev/lightning/intermediate/sota_scaling_techniques.md
        - Important! Effective Training Techniques (Acc grad,cliping): dev/lightning/intermediate/effective_training_techniques.md
        - Deploy Models into Production: dev/lightning/intermediate/deploy_models_into_production.md
      - Advanced:
        - Configure hyperparameters from the CLI: dev/lightning/advanced/hyperparameters_from_the_cli.md
        - Customize training loop: dev/lightning/advanced/own_your_loop.md
  - Models:
    - Convolution Blocks:
      - References: models/conv_blocks/readme.md
      - Activation: models/conv_blocks/activation.md
      - Conv1d: models/conv_blocks/conv1d.md
      - BSConv: models/conv_blocks/bsconv.md
      - Conv1dGLU: models/conv_blocks/conv1d_glu.md
      - ConvTransposed: models/conv_blocks/conv_transposed.md
      - CoordConv1d: models/conv_blocks/coord_conv1d.md
      - AddCoords: models/conv_blocks/add_coords.md
    - Attention:
      - References: models/attention/readme.md
      - Conformer: models/attention/conformer.md
      - Feed Forward: models/attention/feed_forward.md
      - Style Embed Attention: models/attention/style_embed_attention.md
      - Multi-Head Attention: models/attention/multi_head_attention.md
      - Relative Multi-Head Attention: models/attention/relative_multi_head_attention.md
      - Conformer Multi-Headed Self Attention: models/attention/conformer_multi_headed_self_attention.md
      - Conformer Convolution Module: models/attention/conformer_conv_module.md
      - Conformer Block: models/attention/conformer_block.md
    - Acoustic Model:
      - Aligner: models/acoustic_model/aligner.md
      - References: models/acoustic_model/readme.md
      - Accoustic Model: models/acoustic_model/acoustic_model.md
      - Embedding: models/acoustic_model/embedding.md
      - Helpers: models/acoustic_model/helpers.md
      - Variance Predictor: models/acoustic_model/variance_predictor.md
      - Pitch Adaptor: models/acoustic_model/pitch_adaptor.md
      - Pitch Adaptor2: models/acoustic_model/pitch_adaptor2.md
      - Length Adaptor: models/acoustic_model/length_adaptor.md
      - Phoneme Prosody Predictor: models/acoustic_model/phoneme_prosody_predictor.md
      - Aligner:
        - Monotonic Alignments Shrink: models/acoustic_model/mas.md
    - Config:
      - References: models/config/readme.md
      - Langs: models/config/langs.md
    - Reference Encoder:
      - References: models/reference_encoder/readme.md
      - Style Token Layer (STL): models/reference_encoder/STL.md
      - Reference Encoder: models/reference_encoder/reference_encoder.md
      - Utterance Level Prosody Encoder: models/reference_encoder/utterance_level_prosody_encoder.md
      - Phoneme Level Prosody Encoder: models/reference_encoder/phoneme_level_prosody_encoder.md
    - Univnet:
      - References: models/univnet/readme.md
      - Univnet: models/univnet/univnet.md
      - Traced Univnet: models/univnet/traced_univnet.md
      - Kernel Predictor: models/univnet/kernel_predictor.md
      - LVC Block: models/univnet/lvc_block.md
      - Discriminator: models/univnet/discriminator.md
      - DiscriminatorP: models/univnet/discriminator_p.md
      - DiscriminatorR: models/univnet/discriminator_r.md
      - Multi Period Discriminator: models/univnet/multi_period_discriminator.md
      - Multi Resolution Discriminator: models/univnet/multi_resolution_discriminator.md
    - Helpers:
      - References: models/helpers/readme.md
      - Initializer: models/helpers/initializer.md
      - Tools: models/helpers/tools.md
  - Training:
    - References: training/readme.md
    - Modules:
      - References: training/modules/readme.md
      - Acoustic Module: training/modules/acoustic_module.md
      - Vocoder Module: training/modules/vocoder_module.md
    - Loss:
      - References: training/loss/readme.md
      - Acoustic Losses:
        - Binary Cross Entropy Loss: training/loss/bin_loss.md
        - Forward Sum Loss: training/loss/forward_sum_loss.md
        - FastSpeech 2 Loss: training/loss/fast_speech_2_loss_gen.md
      - Voicoder Losses:
        - STFT: training/loss/stft.md
        - STFT Loss: training/loss/stft_loss.md
        - Log STFT Magnitude Loss: training/loss/log_stft_magnitude_loss.md
        - Spectral Convergence Loss: training/loss/spectral_convergence_loss.md
        - Multi Resolution STFT Loss: training/loss/multi_resolution_stft_loss.md
        - Univnet loss: training/loss/univnet_loss.md
    - Datasets:
      - References: training/dataset/readme.md
      - Libri TTS dataset acoustic: training/dataset/libritts_dataset_acoustic.md
      - Libri TTS dataset vocoder: training/dataset/libritts_dataset_vocoder.md
    - Preprocess:
      - References: training/preprocess/readme.md
      - Audio: training/preprocess/audio.md
      - Audio Processor: training/preprocess/audio_processor.md
      - compute_yin: training/preprocess/compute_yin.md
      - Normalize Text: training/preprocess/normalize_text.md
      - Preprocess LibriTTS: training/preprocess/preprocess_libritts.md
      - TacotronSTFT: training/preprocess/tacotron_stft.md
      - Wav2Vec Aligner: training/preprocess/wav2vec_aligner.md
    - Tools: training/tools.md
  - Experiments:
    - References: experiments/readme.md
    - MAS torch: experiments/mas_torch.md
    - Conv Leaky ReLU: experiments/conv_leaky_relu.md
    - Tokenization: experiments/tokenization.md
    - Optimizer:
      - References: experiments/optimizer/readme.md
      - Scheduled Optim Pretraining: experiments/optimizer/scheduled_optim_pretraining.md
      - Scheduled Optim Finetuning: experiments/optimizer/scheduled_optim_finetuning.md
  - About mkdocs-material: readme.md
theme:
  name: material
  features:
  - navigation.footer
markdown_extensions:
  - pymdownx.superfences
plugins:
- search
- mkdocstrings:
    default_handler: python
extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.css
