site_name: TTS-Framework
nav:
  - Home: index.md
  - Model:
    - Convolution Blocks:
      - References: model/conv_blocks/readme.md
      - Activation: model/conv_blocks/activation.md
      - Conv1d: model/conv_blocks/conv1d.md
      - BSConv: model/conv_blocks/bsconv.md
      - Conv1dGLU: model/conv_blocks/conv1d_glu.md
      - ConvTransposed: model/conv_blocks/conv_transposed.md
      - CoordConv1d: model/conv_blocks/coord_conv1d.md
      - AddCoords: model/conv_blocks/add_coords.md
    - Attention:
      - References: model/attention/readme.md
      - Style Embed Attention: model/attention/style_embed_attention.md
      - Relative Multi-Head Attention: model/attention/relative_multi_head_attention.md
      - Conformer Multi-Headed Self Attention: model/attention/conformer_multi_headed_self_attention.md
    - Acoustic Model:
      - References: model/acoustic_model/readme.md
      - Embedding: model/acoustic_model/embedding.md
      - Variance Predictor: model/acoustic_model/variance_predictor.md
      - Pitch Adaptor: model/acoustic_model/pitch_adaptor.md
      - Length Adaptor: model/acoustic_model/length_adaptor.md
      - Phoneme Prosody Predictor: model/acoustic_model/phoneme_prosody_predictor.md
      - Feed Forward: model/acoustic_model/feed_forward.md
      - Aligner:
        - Monotonic Alignments Shrink: model/acoustic_model/mas.md
    - Reference Encoder:
      - References: model/reference_encoder/readme.md
      - Style Token Layer (STL): model/reference_encoder/STL.md
      - Reference Encoder: model/reference_encoder/reference_encoder.md
      - Utterance Level Prosody Encoder: model/reference_encoder/utterance_level_prosody_encoder.md
      - Phoneme Level Prosody Encoder: model/reference_encoder/phoneme_level_prosody_encoder.md
  - Helpers:
    - References: helpers/readme.md
    - Tools: helpers/tools.md
  - About mkdocs-material: readme.md
theme:
  name: material
  features:
  - navigation.footer
markdown_extensions:
  - pymdownx.superfences
plugins:
- search
- mkdocstrings:
    default_handler: python
extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.css
