[tool.ruff]
fixable = ["ALL"]

ignore = ["A003", "T201", "B006", "B008", "B904", "PT009", "PD901", "F403", "E501", "F401", "FA100", "FA102", "ANN003", "ANN101", "ANN204", "ANN201", "FIX002", "FBT002", "FBT001", "FBT003", "TD003", "TD002", "TCH001", "TCH002", "D100", "D101", "D102", "D107", "D401", "D205", "PLR0913", "PLR0915", "PT027", "PTH113", "PTH118", "PTH123", "ERA001", "RET505", "D104", "D407", "D400", "D406", "D413", "D415", "EM101", "EM102", "TRY003", "S101", "N802", "N803", "N806", "N812", "N815", "N999", "RUF001", "RUF003", "RET504", "PLR5501", "EXE002", "INP001", "E731"]
ignore-init-module-imports = true

select = ["ALL"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.isort]
force-sort-within-sections = true
# order-by-type = true

[tool.pyright]
typeCheckingMode = "basic"
include = ["model", "training"]
exclude = []
ignore = []

defineConstant = { DEBUG = true }

reportMissingImports = true
reportMissingTypeStubs = false
reportMissingTypeStubsSeverity = "error"

[tool.ruff.flake8-type-checking]
strict = true

